Metrics/ModuleLength:
  Exclude:
    - "spec/*_spec.rb"

Metrics/BlockLength:
  Exclude:
    - "spec/*_spec.rb"

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
